create new document
f1resh/OSDevNotepad pull request #10
Opened 2023-09-07 20:15 UTC by sssgitex

создание исходного документа при открытии и создание новых при нажатии кнопки

2023-09-12 17:08 UTC, f1resh requested changes
Исправь ошибки, если что могу объяснить показать

2023-09-12 17:08 UTC, f1resh commented on mainwindow.cpp
> +    //ui->setupUi(this);
ui надо оставить, в нём будут статические меню и тулбар

2023-09-12 17:08 UTC, f1resh commented on mainwindow.cpp
> +//    mdi -> currentSubWindow()->setWindowTitle("Новый 1");
эти две строки удалить

2023-09-12 17:08 UTC, f1resh commented on mainwindow.cpp
> +    testButton -> raise();
всё что касается кнопки надо удалить, в конечном коде этого не должно быть
ты можешь тестировать с кнопкой, но в пулл-реквесте этого не должно быть

2023-09-12 17:08 UTC, f1resh commented on mainwindow.cpp
> +    QObject::connect(testButton, SIGNAL(clicked()), mdi,SLOT(&MdiMain::slotOpenNewDoc(&mdi)));
сигнал тоже нужно удалить

2023-09-12 17:08 UTC, f1resh commented on mainwindow.h
> +    MdiMain *mdi;
сделать forward declaration MdiMain

2023-09-12 17:08 UTC, f1resh commented on mainwindow.h
> +#include "mdimain.h"
убрать этот инклюд, чтоб сделать forward declaration

2023-09-12 17:08 UTC, f1resh commented on mainwindow.h
> +    QPushButton *testButton;
кнопку убрать

2023-09-12 17:08 UTC, f1resh commented on mdimain.h
> +    QMdiArea *mdi;
это не нужно, у тебя объект сам является QMdiArea, можно к нему обращаться через this, поэтому этот поинтер не нужен

2023-09-12 17:08 UTC, f1resh commented on mdimain.h
> +    MdiMain(QMdiArea *parent = nullptr)
здесь нужно в конструкторе сделать следующее:
MdiMain(QWidget *parent = nullptr) : QMdiArea(parent)

2023-09-12 17:08 UTC, f1resh commented on mdimain.h
> +        mdi -> addSubWindow(new QTextEdit());
везде убрать mdi, можно заменить на this
можно просто вызывать функции, т.к. сам класс уже является QMdiArea

2023-09-12 17:08 UTC, f1resh commented on mdimain.h
> +//    }
убрать все комментарии

2023-09-12 17:08 UTC, f1resh commented on mdimain.h
> +    void slotOpenNewDoc(MdiMain *mdi);
зачем тут аргумент передаётся слоту, функция все равно не использует этот аргумент

2023-09-12 17:08 UTC, f1resh commented on mdimain.cpp
> +void MdiMain::slotOpenNewDoc(MdiMain *mdi)
зачем тут у функции аргумент?
она его не использует

2023-09-12 17:08 UTC, f1resh commented on mdimain.cpp
> +    mdi -> addSubWindow(new QTextEdit());
убрать mdi, использовать this или просто вызов функции
в конструкторе QTextEdit указать (this) в аргументе для garbage collector

2023-09-12 17:08 UTC, f1resh commented on mainwindow.cpp
> +#include <QGridLayout>
убрать неиспользуемые include

2023-09-14 18:32 UTC, f1resh requested changes

2023-09-14 18:32 UTC, f1resh commented on mdimain.h
> +        this -> nameDoc();
удалить, это не надо
созданием вкладок в конструкторе не надо заниматься :)

2023-09-14 18:32 UTC, f1resh commented on mdimain.h
> +    QString docNameText;
это зачем?

2023-09-14 18:32 UTC, f1resh commented on mdimain.h
> +#include "qtextedit.h"
это заменить на <QTextEdit>

2023-09-14 18:32 UTC, f1resh commented on mdimain.h
> +#include <QPushButton>
пушбаттон не нужен

2023-09-14 18:32 UTC, f1resh commented on mdimain.h
> +        this -> setTabsMovable(true);
конструктор перенести в cpp файл

2023-09-17 19:52 UTC, f1resh approved these changes
все ок

2023-09-18 09:33 UTC, Erge-S approved these changes
Ok

2023-09-18 09:34 UTC, merged