Add files via upload
f1resh/OSDevNotepad pull request #17
Opened 2023-09-19 04:56 UTC by RozaBlack

Добавлено диалоговое окно для перехода к строке с указанным номером.

2023-09-20 20:39 UTC, f1resh requested changes

2023-09-20 20:39 UTC, f1resh commented on dialoggotostring.cpp
> +    : QDialog(parent, Qt::WindowTitleHint | Qt::WindowSystemMenuHint)
как этот класс узнает в каком окне ему нужно перейти на строку?
название Класса должно быть с большой буквы

2023-09-20 20:39 UTC, f1resh commented on dialoggotostring.h
> +class dialogGoToString : public QDialog
Название Класса с большой буквы

2023-09-21 20:41 UTC, RozaBlack commented on dialoggotostring.h
> +#include <QLabel>
Насколько я поняла, это означает, что нужно объявить их так:
    class QPushButton;
    class QGridLayout;
    class QSpinBox;
    class QLabel;
Однако в таком случае появляется ошибка: 
    Allocation of incomplete type 'имя класса'
Подскажите, пожалуйста, как её можно исправить?

2023-09-26 17:35 UTC, f1resh commented on dialoggotostring.cpp
> +    m_lineNumber = new QSpinBox;
Спинбокс ограничен по значениям - не получается ввести трехзначное число

2023-10-06 09:23 UTC, f1resh approved these changes

2023-10-06 09:29 UTC, Erge-S approved these changes

2023-10-06 09:30 UTC, qmanboy approved these changes

2023-10-06 09:30 UTC, merged