Feature/us8 t1 t4 statusbar
f1resh/OSDevNotepad pull request #28
Opened 2023-10-06 18:46 UTC by qmanboy

Добавлен класс отображения статистики текста текущего документа StatusBar, добавлен хоткей к печати, задокументирован StatusBar и SearchController

2023-10-06 19:39 UTC, Erge-S submitted a review, later dismissed

2023-10-06 22:32 UTC, f1resh requested changes

2023-10-06 22:32 UTC, f1resh commented on statusbar.h
> +public:
Добавить Q_OBJECT

2023-10-06 22:32 UTC, f1resh commented on statusbar.cpp
> +    this->addLabels();
зачем он тут нужен, я не очень понял

2023-10-06 22:32 UTC, f1resh commented on statusbar.cpp
> +    connect(mdiMain, SIGNAL(subWindowActivated(QMdiSubWindow*)), this, SLOT(changeTxt()));
addLabels() можно здесь вызывать уже

2023-10-06 22:32 UTC, f1resh commented on statusbar.cpp
> +    connect(mdiMain, SIGNAL(subWindowActivated(QMdiSubWindow*)), this, SLOT(changeTxt()));
если сделать changeTxt(QSubWindow*) - то можно прям через сигнал-слот передавать ссылку на активную вкладку, и там уже пытаться внутри метода кастить к QTextEdit, но это так - просто мысли вслух, твой вариант тоже хорош

2023-10-07 21:00 UTC, f1resh approved these changes

2023-10-07 21:01 UTC, Erge-S approved these changes

2023-10-07 21:01 UTC, merged